# Generated by Django 3.1 on 2020-09-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='town_city',
        ),
    ]
