# Generated by Django 3.1 on 2020-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_auto_20200905_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='comp',
            name='size_range',
            field=models.CharField(max_length=254),
        ),
    ]
