# Generated by Django 3.1 on 2020-09-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0005_remove_comp_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
